### ISSUE TITLE
SetSite failed for package [PreviewJSON] - MissingMethodException InfoBarModel constructor

### ISSUE THREAD

**Issue by KyleKolander** [viacheslav-lozinskyi/Preview-JSON#1]
Something in the last couple commits you made (past few days) broke all of your preview extensions with Visual Studio 2022 (tested on Enterprise edition 17.0.4).  It is all still working for me on one of my machines since I haven't updated the extensions yet.  On my other machine, I had yet to install your extensions until today, and I get this error.  When starting VS, an error pops up for each of your Preview extensions.  Restarting does not help.

![PreviewJSON](https://user-images.githubusercontent.com/22461822/148460869-9a12d48c-8992-4420-a4f2-a3204a628ee6.png)

Works:
```
<Identity Id="PREVIEW-JSON.EC198F83-B43E-48F7-A346-3BA545D132DE" Version="1.0.8" Language="en-US" Publisher="Viacheslav Lozinskyi" />
<Identity Id="METAOUTPUT.2022.2DEDB4CB-B638-4121-874B-191C988DFC69" Version="2.0.8.190" Language="en-US" Publisher="Viacheslav Lozinskyi" />
```

Doesn't work:
```
<Identity Id="PREVIEW-JSON.EC198F83-B43E-48F7-A346-3BA545D132DE" Version="1.0.10" Language="en-US" Publisher="Viacheslav Lozinskyi" />
<Identity Id="METAOUTPUT.2022.2DEDB4CB-B638-4121-874B-191C988DFC69" Version="2.0.9.191" Language="en-US" Publisher="Viacheslav Lozinskyi" />
```

This is probably unrelated because it is the same on both machines, but the extensions.vsext file for the PreviewJSON extension references the 2019 METAOUTPUT instead of the 2022 METAOUTPUT.
```
{
  "name": "Used extensions",
  "description": "Used extensions which is necessary for correct work of this plug-in",
  "version": "1.0",
  "extensions": [
    {
      "name": "MetaOutput",
      "vsixId": "METAOUTPUT.2019.2DEDB4CB-B638-4121-874B-191C988DFC69"
    }
  ]
}
```

Here's the relevant output from ActivityLog.xml (cleaned up for display):

```
SetSite failed for package [PreviewJSON]
Source: "preview-json.vs"
Description: Method not found:
Void Microsoft.VisualStudio.Shell.InfoBarModel..ctor(System.Collections.Generic.IEnumerable`1<Microsoft.VisualStudio.Shell.Interop.IVsInfoBarTextSpan>
                                                   , System.Collections.Generic.IEnumerable`1<Microsoft.VisualStudio.Shell.Interop.IVsInfoBarActionItem>
                                                   , Microsoft.VisualStudio.Imaging.Interop.ImageMoniker
                                                   , Boolean)
System.MissingMethodException: 
Method not found: 
Void Microsoft.VisualStudio.Shell.InfoBarModel..ctor(System.Collections.Generic.IEnumerable`1<Microsoft.VisualStudio.Shell.Interop.IVsInfoBarTextSpan>
                                                   , System.Collections.Generic.IEnumerable`1<Microsoft.VisualStudio.Shell.Interop.IVsInfoBarActionItem>
                                                   , Microsoft.VisualStudio.Imaging.Interop.ImageMoniker
                                                   , Boolean)
at resource.package.PreviewJSON.InfoBarService.Validate()
at resource.package.PreviewJSON.<InitializeAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.VisualStudio.Shell.AsyncPackage.<>c__DisplayClass20_0.<<Microsoft-VisualStudio-Shell-Interop-IAsyncLoadablePackageInitialize-Initialize>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.VisualStudio.Threading.JoinableTask.<JoinAsync>d__76.MoveNext()
--- End of stack trace from previous location where exception was thrown
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at Microsoft.VisualStudio.Services.VsTask.RethrowException(AggregateException e)
at Microsoft.VisualStudio.Services.VsTask.InternalGetResult(Boolean ignoreUIThreadCheck)
```

**Comment by KyleKolander** [comment]
I'm only opening an issue for this extension, but it applies to all of your preview extensions.  Hopefully you can fix them soon!

**Comment by viacheslav-lozinskyi** [comment]
I know about this bug, and it is already fixed.
New releases of all extensions are in Visual Studio Marketplace.

Fixed extensions are working correctly, but message which you see will be shown until you press "No" button on this dialog.

The problem was in wrong version of standard libraries used in projects.
You can look fix in the last commit.

Thank you for reported bug.

**Comment by KyleKolander** [comment]
I upgraded the extensions on my first machine and confirmed that the bug happens there now, too.

Then I clicked "No" on each of the preview extension error dialogs, closed VS and reopened it, and confirmed that those error dialogs don't show up anymore.

However, the errors are still present in the VS ActivityLog.xml each time VS starts.  Clicking "No" just suppresses the error.

I looked at your last commit, but I don't see the "fix".  :)  However, I do see that you introduced a new class InfoBarService in VSPackage.cs, though.  The new errors involve InfoBarModel, so it seems an awful lot like you introduced a new bug and have not fixed it yet.

I can preview JSON documents, so it appears to be working... at least for the use case I tested.  I guess it's up to you if  you want to fix the bug or not.  If you do, let me know and I'll happily change my rating/review on the VS Marketplace.

Regardless, it's not a good user experience to force those using your extensions to have to click "No" on an error dialog whenever they install your extensions.  I'm willing to bet a decent number of users would just uninstall, which would be unfortunate because you have a pretty cool set of extensions here.

**Comment by viacheslav-lozinskyi** [comment]
1. Any found bug will be fixed;
2. This bug is already fixed and workable extensions are already published;
2. Not necessary to force me do it;
3. I don't remember any your review for any my project (at least positive);
4. I see only negative [review](https://marketplace.visualstudio.com/items?itemName=ViacheslavLozinskyi.Preview-JSON&ssr=false#review-details) from you;
5. As I understand it's your gratitude;
6. Be consistent and uninstall MetaOutput, all extensions to it and never use this tool;
7. About "not a fix" - below you can see captured video where everything is working.

https://user-images.githubusercontent.com/51988029/148522672-f5ef6970-413f-4fec-abe3-49406a0a3380.mp4
